incubateur-ademe/benefriches

pnpm-lock.yaml, web/package.json
Finalement le webserver de vite fait très bien le taf étant donné que notre conf nginx est minimale pour l'instant
=> Use vite webserver instead of local-web-server dep to serve built webapp in dev

apps/web/.eslintrc.cjs, apps/web/jest.config.ts, apps/web/package.json, apps/web/src/components/pages/SiteFoncier/Create/StateMachine.spec.ts, apps/web/src/components/pages/SiteFoncier/Create/StateMachine.ts, apps/web/tsconfig.json, pnpm-lock.yaml
Documentation de xstate : https://xstate.js.org/docs/
=> feat: use xstate to modelize site foncier form creation

apps/web/src/appDependencies.ts, apps/web/src/features/create-project/application/createProject.actions.ts, apps/web/src/features/create-project/application/createProject.reducer.ts, apps/web/src/features/create-project/domain/project.types.ts, apps/web/src/features/create-project/domain/stakeholders.spec.ts, apps/web/src/features/create-project/infrastructure/save-project-service/localStorageSaveSiteService.ts, apps/web/src/features/create-project/views/confirmation/ProjectCreationConfirmation.tsx, apps/web/src/features/create-project/views/confirmation/index.tsx, apps/web/src/features/create-project/views/costs/introduction/index.tsx, apps/web/src/features/create-project/views/name-and-description/index.tsx, apps/web/src/features/create-project/views/stakeholders/conversion-full-time-jobs-involved/index.tsx, apps/web/src/features/create-project/views/stakeholders/operator/SiteOperatorForm.tsx, apps/web/src/features/create-project/views/stakeholders/operator/index.tsx, apps/web/src/features/create-project/views/stakeholders/reinstatement-contract-owner/index.tsx, apps/web/src/features/create-site/views/confirmation/SiteCreationConfirmation.tsx, apps/web/src/features/projects/infrastructure/projects-list-service/localStorageProjectsListApi.spec.ts, apps/web/src/features/projects/infrastructure/projects-list-service/localStorageProjectsListApi.ts, apps/web/src/store.ts, apps/web/src/test/testAppDependencies.ts
⚠️ Non fonctionnel de bout en bout à cause d'une incohérence sur les données propriétaire/opérateur entre formulaire site et formulaire projet, en cours de résolution
=> Save project in local storage

apps/web/src/App.tsx, apps/web/src/features/create-site/views/documents/SiteDocumentsPage.tsx, apps/web/src/features/create-site/views/documents/index.tsx, apps/web/src/features/onboarding/views/index.tsx, apps/web/src/router.ts
Ajout de l’écran « Documents utiles » avant de passer à la création du site
=> feat: add useful documents screen on create site form

apps/web/src/features/projects/views/project-impacts-page/ProjectImpactsPage.tsx, apps/web/src/features/projects/views/project-impacts-page/charts/CarbonStorageChart.tsx, apps/web/src/features/projects/views/project-impacts-page/charts/SocioEconomicBenefitsBarChart.tsx, apps/web/src/features/projects/views/project-impacts-page/charts/SocioEconomicBenefitsByDomainChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/ProjectsImpactsComparisonPage.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/carbon-emission/CarbonEmissionComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/carbon-storage/CarbonStorageComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/economic-evaluation/EconomicEvaluationComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/economic-impacts/RentIncomeComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/economic-impacts/SecuringCostComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/economic-impacts/TaxRevenueComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/ecosystem-financial-impacts/CarbonStorageEmissionFinancialImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/ecosystem-financial-impacts/EnergyProductionCarbonEmissionFinancialImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/ecosystem-financial-impacts/EnvironmentImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/ecosystem-financial-impacts/PollinationFinancialImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/ecosystem-financial-impacts/WaterCycleFinancialImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/ecosystem-financial-impacts/WaterRegulationFinancialImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/full-time-jobs/FullTimeJobsComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/full-time-jobs/OperationsFullTimeJobsComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/full-time-jobs/ReconversionFullTimeJobsComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/socioeconomic-benefits/SocioEconomicBenefitsComparisonByDomainChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/socioeconomic-benefits/SocioEconomicBenefitsComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/socioeconomic-impacts/SocioEconomicImpactComparison.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/soil-impacts/NonPollutedSoilsImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/soil-impacts/PermeableSoilsImpactComparisonChart.tsx, apps/web/src/features/projects/views/shared/actions/ActionBar.tsx, apps/web/src/features/projects/views/shared/sharedChartConfig.ts
Le premier commit n'est pas très utile à review, c'est un fichier déplacé
=> Add missing charts to project impact page

apps/web/src/features/create-project/views/soils/soils-summary/ProjectSoilsSummary.tsx, apps/web/src/features/create-project/views/soils/soils-surface-areas/FlatSurfacesNotice.tsx, apps/web/src/features/create-project/views/soils/soils-surface-areas/ImpermeableSurfacesNotice.tsx, apps/web/src/features/create-project/views/soils/soils-surface-areas/MineralSoilSurfaceNotice.tsx, apps/web/src/features/create-site/views/soil-contamination/SoilContaminationForm.tsx, apps/web/src/features/create-site/views/soils/soils-summary/SiteSoilsSummary.tsx, apps/web/src/features/create-site/views/soils/soils-surface-areas/SoilsSurfaceAreasForm.tsx, apps/web/src/features/create-site/views/surface-area/SiteSurfaceAreaForm.tsx, apps/web/src/features/projects/views/project-impacts-page/ProjectImpactsPage.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/soil-impacts/NonPollutedSoilsImpactComparisonChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/soil-impacts/PermeableSoilsImpactComparisonChart.tsx, apps/web/src/shared/views/components/Charts/SurfaceAreaPieChart.tsx, apps/web/src/shared/views/components/SurfaceArea/SurfaceArea.tsx
https://www.notion.so/accelerateur-transition-ecologique-ademe/R-gle-typographique-partout-m-et-non-m2-48dbcd8c90d144299eea567caf948791?pvs=4
=> Display square meters areas with unit ㎡ instead of m2

apps/web/package.json, apps/web/postcss.config.js, apps/web/src/features/projects/views/project-impacts-page/impacts/carbon-storage/CarbonStorageChart.tsx, apps/web/src/features/projects/views/projects-impacts-comparison/charts/carbon-storage/CarbonStorageComparisonChart.tsx, apps/web/src/main.css, apps/web/src/main.tsx, apps/web/src/shared/domain/soils.ts, apps/web/src/theme.ts, apps/web/tailwind.config.js, apps/web/tsconfig.json, pnpm-lock.yaml
J’ai ajouté un préfixe "tw-" dans la config tailwind pour éviter les conflits avec le dsfr (même si c’est peu probable qu’il y ait des classes en commun)
=> feat: implements specific colors for soils categories

apps/web/src/app/application/appDependencies.ts, apps/web/src/app/application/store.ts, apps/web/src/features/create-project/application/createProject.actions.ts, apps/web/src/features/create-project/application/createProject.reducer.ts, apps/web/src/features/create-project/domain/project.types.ts, apps/web/src/features/create-project/domain/projectName.ts, apps/web/src/features/create-project/infrastructure/save-project-service/HttpSaveReconversionProjectService.ts, apps/web/src/features/create-project/infrastructure/save-project-service/localStorageSaveSiteService.ts, apps/web/src/features/create-project/views/costs/yearly-projected-costs/index.tsx, apps/web/src/features/create-project/views/name-and-description/index.tsx, apps/web/src/features/create-project/views/revenue/yearly-projected-revenue/index.tsx, apps/web/src/test/testAppDependencies.ts
Il manque les infos liées au calendrier que je vais ajouter au schéma backend
=> feat(web): save reconversion projects on API

apps/api/src/sites/adapters/primary/sites.controller.integration-spec.ts, apps/web/src/features/create-site/application/createSite.actions.ts, apps/web/src/features/create-site/application/createSite.reducer.spec.ts, apps/web/src/features/create-site/application/createSite.reducer.ts, apps/web/src/features/create-site/application/siteData.mock.ts, apps/web/src/features/create-site/domain/siteFoncier.types.ts, apps/web/src/features/create-site/views/site-management/recent-accidents/FricheRecentAccidentsForm.tsx, apps/web/src/features/create-site/views/summary/SiteDataSummary.tsx, apps/web/src/features/create-site/views/summary/index.tsx
Le schéma utilisé dans le front ne correspondant pas aux clés attendues dans l'API et ce n'était pas testé 😅 
Ça n'arrivera plus quand on partagera les types de l'API via le monorepo 👍
=> fix: fix friche accidents numbers mapping to follow API schema

apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.controller.integration-spec.ts, apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.controller.ts, apps/api/src/reconversion-projects/adapters/secondary/reconversion-project-repository/SqlReconversionProjectRepository.integration-spec.ts, apps/api/src/reconversion-projects/adapters/secondary/reconversion-project-repository/SqlReconversionProjectRepository.ts, apps/api/src/reconversion-projects/core/model/reconversionProject.mock.ts, apps/api/src/reconversion-projects/core/model/reconversionProject.ts, apps/api/src/reconversion-projects/core/usecases/createReconversionProject.usecase.spec.ts, apps/web/src/features/create-project/application/createProject.reducer.ts, apps/web/src/features/create-project/application/createProject.selectors.ts, apps/web/src/features/create-project/application/projectData.mock.ts, apps/web/src/features/create-project/application/saveReconversionProject.action.ts, apps/web/src/features/create-project/domain/project.types.ts, apps/web/src/features/create-project/domain/projectName.spec.ts, apps/web/src/features/create-project/domain/projectName.ts, apps/web/src/features/create-project/views/project-types/ProjectTypesForm.tsx, apps/web/src/features/create-project/views/project-types/index.tsx, apps/web/src/features/create-project/views/renewable-energy-types/RenewableEnergyTypeForm.tsx, apps/web/src/features/create-project/views/renewable-energy-types/index.tsx, apps/web/src/features/create-project/views/summary/index.tsx
Il n'est pas prévu d'avoir plusieurs projets d'aménagement en même temps aujourd'hui, ça va simplifier les travaux sur le détail des coûts d'installation et probablement sur l'ajout de l'aménagement quartiers
=> feat: reconversion projects can have only one development plan

apps/web/src/features/projects/application/projectImpacts.mock.ts, apps/web/src/features/projects/application/projectImpactsEconomicBalance.selectors.spec.ts, apps/web/src/features/projects/application/projectImpactsEconomicBalance.selectors.ts, apps/web/src/features/projects/application/projectImpactsEnvironmental.selectors.spec.ts, apps/web/src/features/projects/application/projectImpactsEnvironmental.selectors.ts, apps/web/src/features/projects/application/projectImpactsSocial.selectors.spec.ts, apps/web/src/features/projects/application/projectImpactsSocial.selectors.ts, apps/web/src/features/projects/application/projectImpactsSocioEconomic.selectors.spec.ts, apps/web/src/features/projects/application/projectImpactsSocioEconomic.selectors.ts, apps/web/src/features/projects/domain/impacts.types.ts, apps/web/src/features/projects/views/project-impacts-page/charts-view/ImpactsChartsSocialSection.tsx, apps/web/src/features/projects/views/project-impacts-page/charts-view/impacts/socio-economic/SocioEconomicImpactsByCategoryChart.tsx, apps/web/src/features/projects/views/project-impacts-page/getImpactLabel.ts, apps/web/src/features/projects/views/project-impacts-page/list-view/sections/SocialListSection.tsx, apps/web/src/features/projects/views/project-impacts-page/list-view/sections/SocioEconomicListSection.tsx, apps/web/src/features/projects/views/shared/socioEconomicLabels.ts
Juste le front pour l’instant, pour tester j’ai importé `mixedUseNeighbourhoodProjectImpactMock` à la place de `data` dans  `fetchReconversionProjectImpacts.action.ts`
=> feat(web): display mixed use neighbourhood economic balance and new impacts

apps/api/src/reconversion-projects/core/model/createReconversionProjectFromSite.ts, apps/api/src/reconversion-projects/core/model/reconversionProject.ts, apps/api/src/reconversion-projects/core/usecases/createExpressReconversionProject.usecase.spec.ts, apps/web/src/features/projects/application/projectImpactsSocial.selectors.ts, apps/web/src/features/projects/views/project-impacts-page/charts-view/ImpactChartCard/ImpactAreaChartCard.tsx
À partir des données de l’onglet "Emploi" du tableur Bénéfriches
=> feat: compute operations and reconversion full time etp for express projects

apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.controller.integration-spec.ts, apps/api/src/reconversion-projects/adapters/secondary/repositories/reconversion-project/SqlReconversionProjectRepository.integration-spec.ts, apps/api/src/reconversion-projects/adapters/secondary/repositories/reconversion-project/SqlReconversionProjectRepository.ts, apps/api/src/reconversion-projects/core/model/reconversionProject.mock.ts, apps/api/src/reconversion-projects/core/model/reconversionProject.ts, apps/api/src/shared-kernel/adapters/sql-knex/migrations/20240829162444_drop_project_phase_details_column_in_reconversion_projects_table.ts, apps/api/src/shared-kernel/adapters/sql-knex/tableTypes.d.ts, apps/web/src/features/create-project/application/createProject.reducer.ts, apps/web/src/features/create-project/application/projectData.mock.ts, apps/web/src/features/create-project/application/saveReconversionProject.action.ts, apps/web/src/features/create-project/domain/project.types.ts, apps/web/src/features/create-project/views/project-phase/ProjectPhaseForm.tsx, apps/web/src/shared/domain/photovoltaicPowerStationProject.ts, apps/web/src/shared/domain/reconversionProject.ts
En attente de la confirmation de Laurent concernant la suppression des options `phaseDetails` car je ne suis pas sûr : https://www.notion.so/accelerateur-transition-ecologique-ademe/Etat-d-avancement-r-gle-de-gestion-8718e3f2aaa8474798aef5080c7153d2
=> feat: update project phase options for pv project and remove phase details data

apps/api/src/reconversion-projects/core/model/createReconversionProjectFromSite.ts, apps/web/src/features/create-project/views/costs/reinstatement-costs/ReinstatementCostsForm.tsx, apps/web/src/features/create-project/views/costs/reinstatement-costs/index.tsx, packages/shared/src/reconversion-projects/index.ts, packages/shared/src/reconversion-projects/reinstatementCosts.ts, packages/shared/src/soils/index.ts, packages/shared/src/soils/soilDistribution.ts
Mise en commun du code de calcul avec celui du back pour le projet express
=> feat: compute default values for reinstatement costs in project form

apps/web/src/app/views/App.tsx, apps/web/src/app/views/pages/home/sections/CallToActionSection.tsx, apps/web/src/app/views/router.ts, apps/web/src/features/create-site/application/createSite.reducer.ts, apps/web/src/features/create-site/views/SiteCreationWizard.tsx, apps/web/src/features/create-site/views/introduction/SiteCreationIntroduction.tsx, apps/web/src/features/create-site/views/introduction/index.tsx, apps/web/src/features/onboarding/index.tsx, apps/web/src/features/projects/views/my-projects-page/MyProjectsPageHeader.tsx, apps/web/src/features/users/views/CreateUserForm/index.tsx
Pas grand chose dans le code mais j'ai créé quelues bugs pendant le développement notamment en commençant plusieurs fois un parcours de création.
C'est corrigé mais je veux bien un check extérieur :)
=> feat(web): add introduction page to site creation flow with right layout

apps/api/docs/db_schema/DATABASE.md, apps/api/docs/db_schema/OTHERS.md, apps/api/docs/db_schema/README.md, apps/api/docs/db_schema/RECONVERSION_PROJECTS.md, apps/api/docs/db_schema/SITES.md
À lire avec le rendu fichier (rich diff) de github, la gestion de l’affichage mermaid est plutôt bien bonne avec la possibilité de zoomer
=> docs: add db entity relationships diagrams

apps/api/src/reconversion-projects/core/model/impacts/development-plans-related/mixedUseNeighbourhoodImpacts.ts, apps/web/src/features/projects/application/projectImpacts.mock.ts, apps/web/src/features/projects/application/projectImpactsSocioEconomic.selectors.ts, apps/web/src/features/projects/domain/impacts.types.ts, apps/web/src/features/projects/views/shared/socioEconomicLabels.ts
En attendant de partager les types entre front et back
=> fix: socio-economic impacts actor types

apps/web/src/features/create-project/views/project-types/ProjectTypesForm.tsx, apps/web/src/features/create-project/views/renewable-energy-types/RenewableEnergyTypeForm.tsx
https://www.notion.so/accelerateur-transition-ecologique-ademe/Formulaires-Pages-avec-des-tuiles-cocher-Nouvelles-r-gles-de-gestion-pour-le-layout-v-1be7c8d2dfae4f4b8b578b3e7830d4fd?pvs=4
=> feat(web): update project type and EnR type tile layout in form to prevent scroll to validate

apps/web/src/features/create-project/application/createProject.reducer.ts, apps/web/src/features/create-project/application/projectSiteLocalAuthorities.reducer.spec.ts, apps/web/src/features/create-project/application/stakeholders.selector.spec.ts, apps/web/src/features/create-project/application/urban-project/urbanProject.actions.ts, apps/web/src/features/create-project/application/urban-project/urbanProject.reducer.ts, apps/web/src/features/create-project/application/urban-project/urbanProject.selectors.ts, apps/web/src/features/create-project/application/urban-project/urbanProject.spec.ts, apps/web/src/features/create-project/domain/urbanProject.ts, apps/web/src/features/create-project/views/urban-project/UrbanProjectCreationWizard.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/UrbanProjectCustomSteps.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/index.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/development-plan-introduction/UrbanSpacesDevelopmentPlanIntroduction.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/development-plan-introduction/index.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/green-spaces/introduction/UrbanGreenSpacesIntroduction.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/green-spaces/introduction/index.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/green-spaces/selection/UrbanGreenSpacesSelection.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/green-spaces/selection/index.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/green-spaces/surface-area-distribution/UrbanGreenSpacesDistribution.tsx, apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/green-spaces/surface-area-distribution/index.tsx, packages/shared/src/reconversion-projects/green-spaces/urbanGreenSpaces.ts, packages/shared/src/reconversion-projects/index.ts
On n'a pas encore les pictos pour les différents espaces verts, j'ai fait la demande à Chloë :)
=> feat(web): create urban green spaces forms

apps/web/src/features/create-site/application/expenses.selectors.ts, apps/web/src/features/create-site/domain/expenses.functions.spec.ts, apps/web/src/features/create-site/domain/expenses.functions.ts, apps/web/src/features/create-site/views/custom/site-management/yearly-expenses/SiteYearlyExpensesForm.tsx, apps/web/src/features/create-site/views/custom/site-management/yearly-expenses/index.tsx, apps/web/src/features/create-site/views/custom/site-management/yearly-expenses/mappers.spec.ts, apps/web/src/features/create-site/views/custom/site-management/yearly-expenses/mappers.ts, packages/shared/src/site/index.ts
@cdhenin J'ai testé beaucoup de cas mais je me suis pris un tunnel sur cette tâche donc suis preneur d'une petite review fonctionnelle si tu as le temps !
=> feat(web): display previously entered data for site yearly expenses
