apps/api/babel.config.cjs
apps/api/package.json
apps/api/test/jest-integration.config.ts
apps/api/test/jest.config.ts
pnpm-lock.yaml

ts-jest is closer to what tsc does and we don't need to add babel plugins (decorators for example) https://kulshekhar.github.io/ts-jest/docs/babel7-or-ts

Use ts-jest instead of babel-preset-typescript to read Typescript file in test

---

apps/web/src/features/create-project/views/soils-surface-areas/SoilsSurfaceAreasForm.tsx
apps/web/src/features/create-site/views/soil-contamination/SoilContaminationForm.tsx
apps/web/src/features/create-site/views/soil-contamination/index.tsx
apps/web/src/features/create-site/views/soils/soils-surface-areas/SoilsSurfaceAreasForm.tsx
apps/web/src/shared/views/components/form/NumericInput/SliderNumericInput.tsx

- Ajout du composant SliderNumericInput sur les pages soil-contamination `SoilContaminationForm` et `SoilsSurfaceAreasForm` dans le formulaire de création de site
- Renommage de certaines variables dans `SoilsSurfaceAreasForm` de `create-project` pour clarifier et aligner sur celui de `create-site`
- Refacto des props de `SliderNumericInput` pour clarifier la différence entre les min et max qui représente les extrémités du slider et les min et max qui représente les valeurs max et min que l’on peut atteindre sur le slider.

feat: implement slider on create site form

---

apps/web/src/features/create-project/domain/project.types.ts
apps/web/src/features/create-project/views/costs/photovoltaic-panels-installation-costs/PhotoVoltaicPanelsInstallationCostsForm.tsx
apps/web/src/features/create-project/views/costs/reinstatement-costs/ReinstatementCostsForm.tsx
apps/web/src/features/create-project/views/costs/yearly-projected-costs/YearlyProjectedCostsForm.tsx
apps/web/src/features/create-project/views/revenue/financial-assistance/ProjectFinancialAssistanceRevenueForm.tsx
apps/web/src/features/create-project/views/revenue/yearly-projected-revenue/ProjectYearlyProjectedRevenueForm.tsx
apps/web/src/features/create-project/views/soils-surface-areas/SoilsSurfaceAreasForm.tsx
apps/web/src/features/create-project/views/stakeholders/conversion-full-time-jobs-involved/ConversionFullTimeJobsInvolvedForm.tsx
apps/web/src/features/create-project/views/stakeholders/operations-full-time-jobs-involved/OperationsFullTimeJobsInvolvedForm.tsx
apps/web/src/features/create-project/views/stakeholders/reinstatement-contract-owner/SiteReinstatementContractOwnerForm.tsx
apps/web/src/features/create-site/application/createSite.actions.ts
apps/web/src/shared/views/components/form/NumericInput/SliderNumericInput.tsx

- fix de typos
- empêcher les valeurs négatives sur les champs numériques du parcours projet
- J’ai ajouté le `optional` dans le schéma de validation du site pour `fullTimeJobsInvolved` pour résoudre l’incohérence avec le form (je validerai mercredi avec Chloë et si c’était l’inverse, je fixerais)
- j’ai changé la valeur d’impacts prévisionnel sur photovoltaïque pour éviter de montrer un impact négatif pour le test
- Correction d’un bug sur l’input associé au slider de surfaces 
- Ajout de marker pour le min et le max sur le slider, pour qu’il soit plus agréable à utiliser si on veut rapidement mettre à 0 ou au max

fixes sur les formulaires de création de site et de projet

---

apps/api/src/carbon-storage/adapters/primary/carbonStorage.controller.integration-spec.ts
apps/api/src/carbon-storage/domain/models/carbonStorage.ts
apps/api/src/carbon-storage/domain/usecases/getCityCarbonStoragePerSoilsCategory.spec.ts
apps/api/src/carbon-storage/domain/usecases/getCityCarbonStoragePerSoilsCategory.ts
apps/api/src/shared-kernel/adapters/sql-knex/seeds/carbonStorage.ts
apps/web/src/features/create-project/application/soilsCarbonStorage.actions.ts
apps/web/src/features/create-project/application/soilsCarbonStorage.reducer.spec.ts
apps/web/src/features/create-site/application/siteSoilsCarbonStorage.actions.ts
apps/web/src/features/create-site/application/siteSoilsCarbonStorage.reducer.spec.ts
apps/web/src/features/create-site/application/siteSoilsCarbonStorage.reducer.ts
apps/web/src/features/projects/application/projectImpacts.actions.ts
apps/web/src/features/projects/application/projectImpacts.reducer.spec.ts
apps/web/src/features/projects/application/projectImpactsComparison.actions.ts
apps/web/src/features/projects/application/projectImpactsComparison.reducer.spec.ts
apps/web/src/shared/views/components/Charts/SoilsCarbonStorageChart.tsx

1. Changement de données pour le graphe de stockage de carbone (formulaire site et projet) : 
- axe y : total carbone stocké pour le type de sol
- axe z : carbone stocké par m² pour le type de sol
2. Modification du tooltip

fix: use carbon storage per square meters instead of superficie in Carbon Storage graph

---

apps/api/src/location-features/adapters/primary/locationFeatures.controller.integration-spec.ts
apps/api/src/location-features/adapters/primary/locationFeatures.controller.ts
apps/api/src/location-features/adapters/primary/locationFeatures.module.ts
apps/api/src/location-features/adapters/secondary/photovoltaic-data-provider/PhotovoltaicGeoInfoSystemApi.mock.ts
apps/api/src/location-features/adapters/secondary/photovoltaic-data-provider/PhotovoltaicGeoInfoSystemApi.ts
apps/api/src/location-features/domain/gateways/PhotovoltaicDataProvider.ts
apps/api/src/location-features/domain/usecases/getPhotovoltaicExpectedPerformanceUseCase.ts
apps/api/src/location-features/domain/usecases/getPhotovoltaicExpectedPerformanceUseCase.usecase.spec.ts
apps/web/src/app/application/appDependencies.ts
apps/web/src/app/application/store.ts
apps/web/src/features/create-project/application/pvExpectedPerformanceStorage.actions.ts
apps/web/src/features/create-project/application/pvExpectedPerformanceStorage.reducer.spec.ts
apps/web/src/features/create-project/application/pvExpectedPerformanceStorage.reducer.ts
apps/web/src/features/create-project/domain/photovoltaic.ts
apps/web/src/features/create-project/infrastructure/photovoltaic-performance-service/photovoltaicPerformanceApi.ts
apps/web/src/features/create-project/infrastructure/photovoltaic-performance-service/photovoltaicPerformanceMock.ts
apps/web/src/features/create-project/views/photovoltaic/expected-annual-production/ExpectedAnnualProductionComputationDetails.tsx
apps/web/src/features/create-project/views/photovoltaic/expected-annual-production/ExpectedAnnualProductionForm.tsx
apps/web/src/features/create-project/views/photovoltaic/expected-annual-production/ExpectedAnnualProductionHint.tsx
apps/web/src/features/create-project/views/photovoltaic/expected-annual-production/index.tsx
apps/web/src/test/testAppDependencies.ts

- Ajout d’un endpoint qui permet de requêter l’API de l’outil [Photovoltaic Geographical Information System
](https://re.jrc.ec.europa.eu/pvg_tools/fr/) porté par la Commission Européenne 
- Ajout d’un service et d’un store dans le front pour récupérer la valeur 
- Ajout du détail du calcul dans la vue

feat: use PGVIS api to compute expected PV annual power performance

---

apps/web/src/features/create-project/views/name-and-description/ProjectNameAndDescriptionForm.tsx
apps/web/src/features/create-project/views/photovoltaic/power/PowerForm.tsx
apps/web/src/features/create-project/views/photovoltaic/power/PowerFromSurfaceForm.tsx
apps/web/src/features/create-project/views/photovoltaic/surface/SurfaceForm.tsx
apps/web/src/features/create-project/views/photovoltaic/surface/SurfaceFromPowerForm.tsx
apps/web/src/features/create-project/views/stakeholders/operator/SiteOperatorForm.tsx
apps/web/src/features/create-project/views/stakeholders/reinstatement-contract-owner/SiteReinstatementContractOwnerForm.tsx
apps/web/src/features/create-site/domain/friche.types.ts
apps/web/src/features/create-site/views/address/AddressForm.tsx
apps/web/src/features/create-site/views/denomination/SiteNameAndDescription.tsx
apps/web/src/features/create-site/views/friche-activity/FricheActivityForm.tsx
apps/web/src/features/create-site/views/site-management/owner/SiteOwnerForm.tsx
apps/web/src/features/create-site/views/site-management/recent-accidents/FricheRecentAccidentsForm.tsx
apps/web/src/features/create-site/views/site-management/tenant/SiteTenantForm.tsx
apps/web/src/features/create-site/views/soil-contamination/SoilContaminationForm.tsx
apps/web/src/features/create-site/views/surface-area/SiteSurfaceAreaForm.tsx
apps/web/src/shared/views/components/form/Fieldset/Fieldset.tsx
apps/web/src/shared/views/components/form/NumericInput/NumericInput.tsx
apps/web/src/shared/views/components/form/RadioButton/RadioButton.tsx
apps/web/src/shared/views/components/form/RequiredLabel/RequiredLabel.tsx

- Ajout d’un composant `RequiredLabel`
- Ajout du label sur les champs obligatoires et modifications de quelques incohérences entre l’état « requis » du formulaire et celui des données
- Ajout de deux composants `RadioButton` et `Fieldset` pour régler le souci de multiple Fieldset dans les écrans avec des inputs intercalés au radiobuttons

feat: rework required questions in forms

---

apps/web/src/features/projects/views/project-impacts-page/ImpactChartCard.tsx
apps/web/src/features/projects/views/project-impacts-page/ImpactsChartsView.tsx
apps/web/src/features/projects/views/project-impacts-page/ProjectImpactsPage.tsx
apps/web/src/features/projects/views/project-impacts-page/impacts/cost-benefit-analysis/CostBenefitAnalysisCard.tsx
apps/web/src/features/projects/views/project-impacts-page/impacts/economic-balance/EconomicBalanceImpactCard.tsx
apps/web/src/features/projects/views/project-impacts-page/impacts/socio-economic/SocioEconomicImpactsCard.tsx
apps/web/src/features/projects/views/project-impacts-page/list-view/ImpactItemRow.tsx
apps/web/src/features/projects/views/project-impacts-page/list-view/ImpactMainTitle.tsx
apps/web/src/features/projects/views/project-impacts-page/list-view/ImpactsListView.tsx
apps/web/src/features/projects/views/project-impacts-page/list-view/SocioEconomicSection.tsx
apps/web/src/features/projects/views/project-impacts-page/modals/ImpactDescriptionModal.tsx
apps/web/src/features/projects/views/project-impacts-page/modals/ModalBreadcrumb.tsx
apps/web/src/features/projects/views/project-impacts-page/modals/cost-benefit-analysis/index.tsx
apps/web/src/features/projects/views/project-impacts-page/modals/economic-balance/index.tsx
apps/web/src/features/projects/views/project-impacts-page/modals/socio-economic/index.tsx

Ajout des modales de description au clic sur les titres (j’ai vu ce point avec Chloë) suivants : 
- Analyse coûts bénéfices
- Bilan de l’opération 
- Impacts socio-économiques
J’ai fait au plus simple pour l’instant (sans le graphe dans la modale comme sur les maquettes) car la modale du dsfr la plus large n’est pas suffisamment large pour mettre le graphe proprement. 
En plus, ça me parait plutôt rentrer dans le design V2 des popins (avec la navigation interne aux popins, le sélecteur de durée inclus, etc.) donc je ne pense pas que ça soit indispensable pour le MVP.
Les pages commencent à devenir chargées (pas mal de passage de props en cascade), j’ai pas osé me lancer dans une refacto maintenant mais il faudra qu’on y passe à un moment ^^.

feat(web): init impact description modals for economic main title sections

---

apps/web/src/app/views/pages/home/sections/CallToActionSection.tsx
apps/web/src/app/views/pages/home/sections/HowItWorksSection.tsx
apps/web/src/app/views/pages/home/sections/SupportedProjectsSection.tsx
apps/web/src/app/views/pages/home/sections/TargetsSection.tsx
apps/web/src/app/views/theme.ts
apps/web/src/features/projects/views/project-impacts-page/ProjectImpactsPageHeader.tsx
apps/web/src/features/projects/views/project-impacts-page/ProjectImpactsPageWrapper.tsx
apps/web/src/features/projects/views/project-impacts-page/charts-view/ImpactChartCard/ImpactChartCard.tsx
apps/web/src/features/projects/views/project-impacts-page/charts-view/impacts/environment/SoilsCarbonStorageImpactCard.tsx
apps/web/src/features/projects/views/project-impacts-page/list-view/ImpactValue.tsx
apps/web/src/features/projects/views/shared/sharedChartConfig.ts
apps/web/src/main.css
apps/web/src/shared/domain/soils.ts
apps/web/src/shared/views/components/Charts/SoilsCarbonStorageChart.tsx
apps/web/src/shared/views/components/Charts/SurfaceAreaPieChart.tsx
apps/web/src/shared/views/layout/HeaderFooterLayout/HeaderFooterLayout.tsx
apps/web/src/shared/views/layout/WizardFormLayout/WizardFormLayout.tsx
apps/web/tailwind.config.js

Pour faire fonctionner Highchart avec le thème sombre du dsfr, il a fallu activer l’option `styledMode` et importer le style par défaut de Highchart directement dans le main.css (https://www.highcharts.com/docs/chart-design-and-style/style-by-css). 
Le fait d’activer `styledMode` pour les graphes implique de ne plus pouvoir utiliser les paramètres de style directement dans l’objet config des graphes (comme les couleurs des zones par exemple), il faut passer par l’assignement des variables de style Highchart dans l’attribut style (exemple dans `shared/views/components/Charts/SurfaceAreaPieChart.tsx`)
C’est moins pratique et moins propre mais je n’ai pas trouvé d’autre solution pour le moment (je ne pensais pas rencontrer autant de problème sur les fixes de ce ticket)

fix(web): dark mode display and use styledMode to true for Highcharts

---

apps/api/src/reconversion-projects/adapters/secondary/reconversion-project-impacts-repository/SqlReconversionProjectImpactsRepository.integration-spec.ts
apps/api/src/reconversion-projects/adapters/secondary/reconversion-project-impacts-repository/SqlReconversionProjectImpactsRepository.ts
apps/api/src/reconversion-projects/domain/model/impacts/economic-balance/economicBalanceImpact.spec.ts
apps/api/src/reconversion-projects/domain/model/impacts/economic-balance/economicBalanceImpact.ts
apps/api/src/reconversion-projects/domain/usecases/computeReconversionProjectImpacts.usecase.spec.ts
apps/api/src/reconversion-projects/domain/usecases/computeReconversionProjectImpacts.usecase.ts
apps/web/src/features/projects/domain/impacts.types.ts
apps/web/src/features/projects/views/project-impacts-page/charts-view/impacts/economic-balance/EconomicBalanceImpactCard.tsx
apps/web/src/features/projects/views/project-impacts-page/list-view/sections/EconomicBalance.tsx

Je suppose que dans le cas où l’aménageur est différent du futur exploitant, les charges et dépenses d’exploitation apparaîtront dans les impacts socio-économiques, j’ai posé la question à Chloë, si elle confirme, je ferais un ticket sur Notion.
Edit: réponse de Laurent, à priori non car ces impacts risque de disparaitre

feat: assign economic balance to project developer instead of futureOperator

---

apps/web/src/features/create-project/views/photovoltaic/power/PowerForm.tsx
apps/web/src/features/create-project/views/photovoltaic/power/PowerFromSurfaceForm.tsx
apps/web/src/features/create-project/views/photovoltaic/surface/SurfaceForm.tsx
apps/web/src/features/create-project/views/photovoltaic/surface/SurfaceFromPowerForm.tsx
apps/web/src/features/create-site/views/site-management/yearly-expenses/SiteYearlyExpensesForm.tsx
apps/web/src/features/create-site/views/site-management/yearly-income/SiteYearlyIncomeForm.tsx
apps/web/src/features/create-site/views/soils/soils-distribution/distribution/by-square-meters/BySquareMeters.tsx
apps/web/src/main.css
apps/web/src/shared/views/components/form/NumericInput/ControlledRowNumericInput.tsx
apps/web/src/shared/views/components/form/NumericInput/RowNumericInput.tsx

- Modification du composant `RowNumericInput` pour gérer visuellement les warnings
- Ne pas bloquer le formulaire si les max conseillés sont dépassés
- Création d’un composant `ControlledRowNumericInput` pour factoriser la logique de `numberToString` et `stringToNumber`

fix: use warning instead of error for photovoltaic power and surface

---

apps/api/src/carbon-storage/adapters/secondary/carbonStorageRepository/SqlCarbonStorageRepository.ts
apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.controller.integration-spec.ts
apps/api/src/reconversion-projects/adapters/secondary/reconversion-project-repository/SqlReconversionProjectRepository.ts
apps/api/src/reconversion-projects/core/usecases/createReconversionProject.usecase.spec.ts
apps/api/src/shared-kernel/adapters/sql-knex/seeds/carbonStorage.ts
apps/api/src/shared-kernel/adapters/sql-knex/seeds/cities.ts
apps/api/src/sites/adapters/primary/sites.controller.integration-spec.ts
apps/api/src/sites/adapters/secondary/site-repository/SqlSiteRepository.ts
apps/api/src/sites/core/usecases/createNewSite.usecase.spec.ts
apps/api/src/users/adapters/primary/users.controller.integration-spec.ts
apps/api/src/users/adapters/secondary/user-repository/SqlUserRepository.integration-spec.ts
apps/api/src/users/core/usecases/createUser.usecase.spec.ts
apps/api/tsconfig.json
packages/shared/tsconfig.json

`noUncheckedIndexedAccess` permet de s'assurer qu'un élément existe bien lorsqu'on y accède via index (array ou objet), par exemple :
```
const myArray: string[] = [];
myArray[0].split(",") // pas d'erreur TS sans la noUncheckedIndexedAccess activée alors qu'il y aura une erreur au runtime
```
`noFallthroughCasesInSwitch ` assure que chaque `case` dans un switch soit "indépendant" et que plusieurs case ne puissent être traversés.
Ces règles étaient activées dans le front mais j'avais oublié de les mettre dans l'API !

chore: make Typescript stricter by enabling noUncheckedIndexedAccess and noFallthroughCasesInSwitch in api and shared package

---

apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.module.ts
apps/api/src/reconversion-projects/core/usecases/createReconversionProject.usecase.spec.ts
apps/api/src/sites/adapters/primary/sites.controller.integration-spec.ts
apps/api/src/sites/adapters/primary/sites.module.ts
apps/api/src/sites/adapters/secondary/site-repository/read/InMemorySiteReadRepository.ts
apps/api/src/sites/adapters/secondary/site-repository/read/SqlSiteReadRepository.integration-spec.ts
apps/api/src/sites/adapters/secondary/site-repository/read/SqlSiteReadRepository.ts
apps/api/src/sites/adapters/secondary/site-repository/write/InMemorySiteRepository.ts
apps/api/src/sites/adapters/secondary/site-repository/write/SqlSiteRepository.integration-spec.ts
apps/api/src/sites/adapters/secondary/site-repository/write/SqlSiteWriteRepository.ts
apps/api/src/sites/core/gateways/SitesReadRepository.ts
apps/api/src/sites/core/gateways/SitesRepository.ts
apps/api/src/sites/core/gateways/SitesWriteRepository.ts
apps/api/src/sites/core/usecases/createNewSite.usecase.spec.ts
apps/api/src/sites/core/usecases/createNewSite.usecase.ts
apps/api/src/sites/core/usecases/getSideById.usecase.spec.ts
apps/api/src/sites/core/usecases/getSiteById.usecase.ts

* Ajout des dépenses, emplois temps plein, description et accidents pour la page "caractéristiques du site"
* Refacto de la query SQL pour récupérer le site et les données liées en une seule requête, preneur de ton avis là-dessus !
* J'ai split le repository pour une version write et une autre read car ils n'utilisent plus la même structure de données

feat(api): split SiteRepository into read and write repositories + add fields to returned site data

---

apps/web/src/features/create-project/application/pvFeatures.selectors.ts
apps/web/src/features/create-project/views/photovoltaic/surface/SurfaceForm.tsx
apps/web/src/features/create-project/views/photovoltaic/surface/SurfaceFromPowerForm.tsx

Les textes d'aide deviennent un maladroit car on explique calculer une surface à partir d'un ratio mais lorsque cette surface calculée est supérieure à la surface du site, on utilise la surface du site dans l'input.
Je vais demander à Chloë de retravailler ça.

feat(web): make it impossible to enter a photovoltaic plant surface area bigger than site

---

apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.controller.ts
apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.module.ts
apps/api/src/reconversion-projects/adapters/secondary/reconversion-project-impacts-repository/SqlReconversionProjectImpactsRepository.ts
apps/api/src/reconversion-projects/core/model/createReconversionProjectFromSite.ts
apps/api/src/reconversion-projects/core/model/mixedUseNeighbourhood.ts
apps/api/src/reconversion-projects/core/model/reconversionProject.ts
apps/api/src/reconversion-projects/core/usecases/createExpressReconversionProject.usecase.spec.ts
apps/api/src/reconversion-projects/core/usecases/createExpressReconversionProject.usecase.ts

J'ai isolé la logique de création avec les valeurs en dur dans un service `MixedUseNeighbourHoodReconversionProjectCreationService`, le reste n'est pas très intéressant.
Par rapport aux données du tableur il manque les coûts de désimperméabilisation et de réstauration écologique des sols ainsi que les recettes.
Je m'en occupe dans un deuxième temps pour que tu puisses t'appuyer sur la base.

feat(api): create route and backend logic for express creation of mixed-use neighbourhood reconversion project

---

apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.controller.ts
apps/api/src/reconversion-projects/adapters/primary/reconversionProjects.module.ts
apps/api/src/reconversion-projects/adapters/secondary/queries/SqlReconversionProjectQuery.ts
apps/api/src/reconversion-projects/core/usecases/getReconversionProjectFeatures.usecase.ts
apps/web/src/app/application/appDependencies.ts
apps/web/src/app/application/store.ts
apps/web/src/features/projects/application/project-features/projectFeatures.actions.ts
apps/web/src/features/projects/application/project-features/projectFeatures.reducer.ts
apps/web/src/features/projects/application/projectImpactsComparison.actions.ts
apps/web/src/features/projects/application/projectImpactsComparison.reducer.ts
apps/web/src/features/projects/domain/projects.types.ts
apps/web/src/features/projects/infrastructure/project-details-service/localStorageProjectDetailsApi.ts
apps/web/src/features/projects/infrastructure/project-features-service/HttpProjectFeaturesService.ts
apps/web/src/features/projects/infrastructure/project-features-service/MockProjectFeaturesService.ts
apps/web/src/features/projects/views/project-page/ProjectImpactsPage.tsx
apps/web/src/features/projects/views/project-page/features/DataLine.tsx
apps/web/src/features/projects/views/project-page/features/DevelopmentPlanFeatures.tsx
apps/web/src/features/projects/views/project-page/features/DevelopmentPlanInstallationExpenses.tsx
apps/web/src/features/projects/views/project-page/features/ProjectFeaturesView.tsx
apps/web/src/features/projects/views/project-page/features/SectionTitle.tsx
apps/web/src/features/projects/views/project-page/features/index.tsx
apps/web/src/features/projects/views/project-page/index.tsx
apps/web/src/features/projects/views/projects-impacts-comparison/ImpactsComparisonHeader/index.tsx
apps/web/src/features/projects/views/projects-impacts-comparison/ProjectsImpactsComparisonPage.tsx
apps/web/src/shared/domain/mixedUseNeighbourhood.ts
apps/web/src/test/testAppDependencies.ts

J'ai gardé la UI avec les onglets pour l'instant mais mis le fetching dans un reducer à part.
Aussi les tabs du dsfr ne font pas de lazy rendering donc les caractéristiques sont chargées lorsque tu arrives sur la page impacts, même si tu la consulteras pas. Le coût de la requête est marginal mais ça va de toute façon changer avec la refonte de cette page.
A noter que j'ai utilisé des subqueries SQL, je trouve ça plus lisible et maintenable et il n'y a pas d'overhead sur la perf.
Tu en penses quoi ?

feat: allow users to look up their projects features on a dedicated page

---

apps/web/src/features/create-project/application/stakeholders.selector.spec.ts
apps/web/src/features/create-project/application/stakeholders.selector.ts
apps/web/src/features/create-project/views/stakeholders/developer/ProjectDeveloperForm.tsx
apps/web/src/features/create-project/views/stakeholders/developer/index.tsx
apps/web/src/features/create-project/views/stakeholders/future-site-owner/FutureSiteOwnerForm.tsx
apps/web/src/features/create-project/views/stakeholders/future-site-owner/index.tsx
apps/web/src/features/create-project/views/stakeholders/operator/SiteOperatorForm.tsx
apps/web/src/features/create-project/views/stakeholders/operator/index.tsx
apps/web/src/features/create-project/views/stakeholders/reinstatement-contract-owner/SiteReinstatementContractOwnerForm.tsx
apps/web/src/features/create-project/views/stakeholders/reinstatement-contract-owner/index.tsx
apps/web/src/features/create-site/application/siteMunicipalityData.reducer.ts
apps/web/src/features/create-site/views/site-management/owner/SiteOwnerForm.tsx
apps/web/src/features/create-site/views/site-management/owner/index.tsx
apps/web/src/features/create-site/views/site-management/site-operator/index.tsx
apps/web/src/features/create-site/views/site-management/tenant/index.tsx
apps/web/src/features/users/domain/user.ts
apps/web/src/features/users/views/CreateUserForm/CreateUserForm.tsx
apps/web/src/features/users/views/CreateUserForm/CreateUserStructureForm.tsx
apps/web/src/features/users/views/CreateUserForm/index.tsx
apps/web/src/shared/infrastructure/administrative-division-service/administrativeDivisionGeoApi.ts

- [Ajout du choix de la collectivité en fonction de l’adresse dans le form identité](https://www.notion.so/accelerateur-transition-ecologique-ademe/Formulaire-Cr-ation-de-compte-changement-et-ajout-d-inputs-64fdbd07249b4479a66699f3963b4df2?pvs=4)
- [Adaptation des formulaires site et projet pour gérer le cas collectivité](https://www.notion.so/accelerateur-transition-ecologique-ademe/Qui-est-le-propri-taire-actuel-de-cette-friche-Nouvelles-r-gles-de-gestion-c846b51ed5874bf18bcb4e3def20c841?pvs=4)

feat (web) : update identity form to specify local authority

---

apps/web/index.html
apps/web/package.json

D’après certaines issues sur le repo [react-dsfr](https://github.com/codegouvfr/react-dsfr) il y a eu des changements sur les imports css pour les icônes (le script `only-include-used-icons`) avec notamment l’ajout d’un hash pour éviter que le cache du navigateur empêche de récupérer le nouveau fichier en cas de nouvelles icônes utilisées.
Le script `only-include-used-icons `qui génère ce hash, d’où le fait que ça change à chaque `pnpm dev`
D’après [la doc](https://react-dsfr.codegouv.studio/ ) avec `vite`, on peut directement importer le fichier css à partir des node_modules dans le `index.html`.
Au `build`, l’import est remplacé par les fichiers avec hash : 
```html
<!doctype html>
<html lang="fr">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, …
```

chore: update react dsfr predev and prebuild scripts and css import in index.html

---

apps/api/src/reconversion-projects/core/model/impacts/socio-economic/computeDirectAndIndirectEconomicImpacts.spec.ts
apps/api/src/reconversion-projects/core/model/impacts/socio-economic/computeDirectAndIndirectEconomicImpacts.ts
apps/api/src/reconversion-projects/core/usecases/computeReconversionProjectImpacts.usecase.ts

l’impact « Dépenses de sécurisation de la friche évités » s’affichait pour les sites non friche car le coût « maintenance » est compté dans les dépenses évités pour la friche, et c’est un coût que l’on peut remplir pour un site non friche (et pré-rempli pour un site express).

fix(api): do not compute avoided friche costs impacts if site is not friche

---

apps/api/src/reconversion-projects/core/gateways/FakeGetSoilsCarbonStorageService.ts
apps/api/src/reconversion-projects/core/model/impacts/socio-economic/computeEnvironmentalMonetaryImpacts.ts
apps/api/src/reconversion-projects/core/model/impacts/soils-carbon-storage/soilsCarbonStorageImpact.ts
apps/api/src/reconversion-projects/core/usecases/computeReconversionProjectImpacts.usecase.spec.ts
apps/api/src/reconversion-projects/core/usecases/computeReconversionProjectImpacts.usecase.ts
apps/web/src/features/projects/application/projectImpacts.mock.ts
apps/web/src/features/projects/application/projectImpactsEnvironmental.selectors.ts
apps/web/src/features/projects/application/projectKeyImpactIndicators.selectors.ts
apps/web/src/features/projects/domain/impacts.types.ts

Lorsque le calcul du carbone dans les sols échouait, tout le usecase était en erreur.
J'ai rencontré le cas pour des friches situées à La Réunion par exemple, territoire pour lequel on a pas d'infos dans les data INSEE.
C'est marginal mais dans tous les cas, il ne faut pas que ce soit un bottleneck 😅

fix: prevent impacts computing failure when soils carbon storage fails

---

apps/web/src/features/create-project/application/urban-project/urbanProject.actions.ts
apps/web/src/features/create-project/application/urban-project/urbanProject.reducer.ts
apps/web/src/features/create-project/application/urban-project/urbanProject.selectors.ts
apps/web/src/features/create-project/application/urban-project/urbanProject.spec.ts
apps/web/src/features/create-project/domain/urbanProject.ts
apps/web/src/features/create-project/views/urban-project/UrbanProjectCreationWizard.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/UrbanProjectCustomSteps.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/index.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/green-spaces/surface-area-distribution/UrbanGreenSpacesDistribution.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/living-and-activity-spaces/introduction/LivingAndActivitySpacesIntroduction.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/living-and-activity-spaces/introduction/index.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/living-and-activity-spaces/selection/LivingAndActivitySpacesSelection.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/living-and-activity-spaces/selection/index.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/living-and-activity-spaces/surface-area-distribution/LivingAndActivitySpacesDistribution.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/living-and-activity-spaces/surface-area-distribution/index.tsx
apps/web/src/features/create-project/views/urban-project/custom-forms/spaces/surface-area/SpacesCategoriesSurfaceAreaDistributionForm.tsx
apps/web/src/features/create-site/views/custom/soils/soils-distribution/distribution/by-percentage/ByPercentageForm.tsx
apps/web/src/features/create-site/views/custom/soils/soils-distribution/distribution/by-square-meters/BySquareMeters.tsx
apps/web/src/shared/views/components/form/SurfaceAreaControlInput/SurfaceAreaControlInput.tsx
packages/shared/src/reconversion-projects/index.ts
packages/shared/src/reconversion-projects/living-and-activity-spaces/urbanLivingAndActivitySpaces.ts

Pas de pictos non plus 😅 
Le code se répète pas mal sur les formulaires de sélection/attribution des surfaces, je vais voir si ça vaut le coup de créer des composants génériques genre `<SpaceSelectionForm/>` et `<SpaceSurfaceAreaDistributionForm/>`, peut-être même généralisable sur les formulaires sols.

feat(web): create urban living and activity spaces forms
